[plushboxesascreeperdrops]
	#If true, plush boxes can be dropped by Creepers
	creepersdropplushboxes = true
	#Chance for Creepers to drop a plush box upon being killed
	creeperplushboxdroppercentage = 5.0
	#If true, modded Creeper variants (tagged as minecraft:creepers) can drop plush boxes too
	modded_creepersdropplushboxes = true
	#If true, looting is considered when calculating the plush box drop rate of Creepers
	lootingaffects_creeperschanceofdroppingplushboxes = true

[plant_plushies]
	#If true, odd trees will generate as plants around your world (Warning!, if this is set to false, Sudowoodo plushies will no longer be obtainable in survival mode
	oddtreesgeneratenaturally = true
	#If true, Pikmin trees will generate as plants aroundin your world
	pikminplushiesgeneratenaturally = true

[plushies_starter_kit]
	#Change how many plush boxes the player starts with when joining a world for the first time
	numberofplushboxestheplayerstartswith = 1.0
	#Change how many golden plush boxes the player starts with when joining a world for the first time
	numberofgoldenplushboxestheplayerstartswith = 0.0

["states&_placement"]
	#If true, placement mode will be enabled. Right clicking with a stick lets you change the state you place your plushies (default, sitting or standing)
	placement_mode = true

[rat]
	#If true, rats will spawn in your world
	spawnrats = true
